commonLabels:
  app: dotnet-template-app

bases:
  - ../../base

namespace: dev-dotnet-template-app

configMapGenerator:
  - name: appsettings
    files:
      - appsettings.json

images:
  - name: ghcr.io/politiet/dotnet-template-app
    newTag: VERSION_TAG

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
  - path: deployment.yaml
    target:
      kind: Deployment