apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: whitelister
spec:
  ipWhiteList:
    sourceRange:
      - 10.11.205.96/27 #tilgang fr책 vpn
      - 163.174.97.0/24 #tilgang fr책 origo
      - 10.144.130.192/27 #tilgang fr책 dpno
      - 10.144.130.96/27 #tilgang fr책 pno
    ipStrategy:
      depth: 1