commonLabels:
  app: dotnet-template

resources:
  - ../../base

namespace: stage-dotnet-template

configMapGenerator:
  - name: appsettings
    files:
      - appsettings.json

images:
  - name: ghcr.io/politiet/dotnet-template
    newTag: VERSION_TAG

patches:
  - path: ingress.yaml
    target:
      kind: Ingress
  - path: deployment.yaml
    target:
      kind: Deployment