name: Add deployment secrets

on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "Environment to run in"
        default: dev
        type: choice
        options:
          - dev
          - test
          - stage
          - prod

jobs:
  setup-env-variables:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      namespace: ${{ vars.NAMESPACE }}

    steps:
      - name: Setup necessary env variables
        run: echo "Vars set"

  create-secrets:
    needs: [ setup-env-variables ]
    uses: politiet/reusable-workflows/.github/workflows/add-deployment-opaque-secrets.yml@main
    with:
      namespace: ${{ needs.setup-env-variables.outputs.namespace }}
      secret_name: ${{ github.event.repository.name }}-secrets
      environment: ${{ inputs.environment }}
    secrets:
      secret_values: |
        {
          "<example-secret-key>": "<example-secret-value>" 
        }
      bks_kubeconfig: ${{ secrets.KUBECONFIG }}

  add-secret-githubkey:
    needs: [ setup-env-variables ]
    uses: politiet/reusable-workflows/.github/workflows/add-deployment-secret.yml@main
    with:
      secret_name: githubkey
      secret_type: kubernetes.io/dockerconfigjson
      secret_key: .dockerconfigjson
      namespace: ${{ needs.setup-env-variables.outputs.namespace }}
      environment: ${{ inputs.environment }}
    secrets:
      bks_kubeconfig: ${{ secrets.KUBECONFIG }}
      secret_value: ${{ secrets.GITHUBKEY }}
